project:
  type: website
  output-dir: "website"

website:
  title: "JSC370 Final Project"
  navbar:
    left:
      - text: "Home"
        href: project/index.qmd
      - text: "Data Exploration (Archive)"
        href: project/data_exploration.qmd
    right:
      - icon: github
        href: https://github.com/ChristopherLi05/JSC370-Final-Project
  page-footer:
    center: "Copyright &copy; 2026 Christopher Li. All rights reserved."

format:
  html:
    theme: darkly
    toc: true
    toc-float: true
    css: project/styles.css
